CORE 386 Bugfixing multile contac Persons added in Basic Data Form
quarano/quarano-application pull request #119
Opened 2020-08-25 14:44 UTC by Tunafleur

2020-08-27 07:15 UTC, VILLAN3LL3 commented
![grafik](https://user-images.githubusercontent.com/39371377/91409498-c690fe80-e845-11ea-866d-7460716310ef.png)
Ein bereits ausgewählter Kontakt darf nicht mehr in der Auswahlliste angezeigt werden.

2020-08-27 07:26 UTC, VILLAN3LL3 requested changes

2020-08-27 07:26 UTC, VILLAN3LL3 commented on frontend/libs/client/feature-enrollment/src/lib/basic-data/basic-data.component.ts
> +              this.secondFormLoading = true;
warum hast du das hier runter gezogen?

2020-08-27 07:26 UTC, VILLAN3LL3 commented on frontend/libs/client/feature-enrollment/src/lib/basic-data/basic-data.component.ts
> +    }
Das wirkt ein bisschen wie ein quickfix. Was ist denn die Ursache dafür, dass sich secondFormLoading nicht ausschaltet? Kann diese Ursache nicht behoben werden?

2020-08-27 07:26 UTC, VILLAN3LL3 commented on frontend/libs/client/feature-enrollment/src/lib/basic-data/basic-data.component.html
> +            (click)="openContactDialog(date.toLocaleDateString('de'), date)"
Wenn das date benötigt wird, fände ich es schöner, hier nur das date zu übergeben und das .toLocaleDateString dann in der openContactDialog-Methode aufzurufen. Was meinst du?

2020-09-16 15:13 UTC, Tunafleur commented on frontend/libs/client/feature-enrollment/src/lib/basic-data/basic-data.component.ts
> +              this.secondFormLoading = true;
@VILLAN3LL3  weil für mich der Loadingmode nur Sinn macht wenn auch wirklich geladen wird und nicht pauschal nach Überprüfung der Formgroup Validität bei Zeile 245, macht das für dich auch Sinn?

2020-10-29 09:37 UTC, closed without merging