Import and consolidate developer documentation
quarano/quarano-application pull request #132
Opened 2020-09-16 21:32 UTC by yliu-02

hab das, was paul mir geschickt hat mit ein paar sachen aus gepinnten messages in slack kombniniert. hab auch selber ein paar kommentare ergänzt. wenn etwas fehlerhaft ist, herausgenommen soll oder irgendwas fehlt, kommentiert einfach. ich editier das dann

2020-09-30 17:37 UTC, VILLAN3LL3 requested changes

2020-09-30 17:37 UTC, VILLAN3LL3 commented on documentation/development/Readme.md
> +  - https://quarano-frontend-dev.cfapps.io/auth/login (DEV Umgebung)
ist der Link noch aktuell?

2020-09-30 17:37 UTC, VILLAN3LL3 commented on documentation/development/Readme.md
> +- Start backend with `mvn spring-boot:run -Pinmemory`, then start frontend with `npm run ng serve`. After that a local test site will be available at http://localhost:4200
Stimmt der Befehl? Ich verwende immer` ./mvnw spring-boot:run -P inmemory`

2020-09-30 17:37 UTC, VILLAN3LL3 commented on documentation/development/Readme.md
> +- Start backend with `mvn spring-boot:run -Pinmemory`, then start frontend with `npm run ng serve`. After that a local test site will be available at http://localhost:4200
Für das Frontend verwende ich immer ng serve (ggf. mit --open, damit sich auch gleich das Browserfenster öffnet)

2020-09-30 17:37 UTC, VILLAN3LL3 commented on documentation/development/Readme.md
> +- Start backend with `mvn spring-boot:run -Pinmemory`, then start frontend with `npm run ng serve`. After that a local test site will be available at http://localhost:4200
Vielleicht wäre es noch wichtig, dass man zunächst einmal `npm i `laufen lassen muss, wenn man das Frontend neu ausgecheckt hat

2020-10-13 10:43 UTC, yliu-02 commented on documentation/development/Readme.md
> +  - https://quarano-frontend-dev.cfapps.io/auth/login (DEV Umgebung)
Habs raus genommen

2020-10-13 10:48 UTC, yliu-02 commented on documentation/development/Readme.md
> +- Start backend with `mvn spring-boot:run -Pinmemory`, then start frontend with `npm run ng serve`. After that a local test site will be available at http://localhost:4200
Die commands ändern sich, wenn mvn und angular-cli auf PATH liegen bzw nicht liegen. Hab das noch zusammen mit npm install ergänzt

2021-01-06 18:36 UTC, patrickotto commented
Transferred process information to confluence. Technical parts are already present in latest readme files

2021-01-06 18:36 UTC, closed without merging