Feature/core 430 create new contact person
quarano/quarano-application pull request #146
Opened 2020-10-31 16:07 UTC by bit-shube

2020-11-01 07:25 UTC, VILLAN3LL3 commented
e2e test failed noch :)

2020-11-02 18:39 UTC, VILLAN3LL3 requested changes

2020-11-02 18:39 UTC, VILLAN3LL3 commented on frontend/apps/quarano-frontend-e2e/src/integration/health-department/contact-cases/contact-cases.spec.ts
> +
ich würd hier noch prüfen, ob die richtige backendurl aufgerufen wird und ob der richtige status zurückkommt

2020-11-04 18:05 UTC, bit-shube commented on frontend/apps/quarano-frontend-e2e/src/integration/health-department/contact-cases/contact-cases.spec.ts
> +
Hab ich angepasst.

2020-11-04 18:11 UTC, VILLAN3LL3 approved these changes

2020-11-04 19:05 UTC, merged